version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: gen
    ports:
      - "9000:9000"
  web2:
    build: ./quote_disp
    container_name: disp
    ports:
      - "9001:9001"
    depends_on:
      - web1